/**
 * WidowBlue – termini tecnici AI (architetture, training, infra, RAG, agenti, safety)
 * Sorgente: elenco completo fornito dall'utente.
 */
export const AI_GLOSSARY = {
  addestramento: { it: 'L\'addestramento (training) è il processo in cui un modello regola i parametri sui dati per ridurre l\'errore.', en: 'Training adjusts model parameters on data to minimize error.' },
  agi: { it: 'AGI indica un\'AI con capacità generali paragonabili a quelle umane su molti compiti.', en: 'AGI means AI with broad human-level abilities across domains.' },
  'agente ai': { it: 'Un agente AI persegue un obiettivo, pianifica e usa strumenti in autonomia.', en: 'An AI agent pursues goals using tools over multiple steps.' },
  'ai generativa': { it: 'L\'AI generativa crea contenuti nuovi (testo, immagini, codice) da pattern appresi.', en: 'Generative AI creates new content from learned patterns.' },
  allucinazione: { it: 'Allucinazione: informazione plausible ma non supportata dai fatti. Si riduce con grounding e RAG.', en: 'Hallucination is plausible but false output; reduced via grounding.' },
  bias: { it: 'Bias: distorsione sistematica nei dati o nelle predizioni.', en: 'Bias is systematic distortion in data or predictions.' },
  'chain of thought': { it: 'Chain of thought: ragionamento a passi interni prima della risposta finale.', en: 'Chain of thought is step-by-step intermediate reasoning.' },
  'catena del pensiero': { it: 'Chain of thought: ragionamento a passi interni prima della risposta finale.', en: 'Chain of thought is step-by-step intermediate reasoning.' },
  dataset: { it: 'Dataset: insieme di esempi per train, validazione o test.', en: 'A dataset is the collection of examples for train/val/test.' },
  'deep learning': { it: 'Deep learning: reti neurali multi-strato per rappresentazioni gerarchiche.', en: 'Deep learning uses multi-layer neural nets.' },
  distillazione: { it: 'Knowledge Distillation: trasferimento di conoscenza da un modello grande (teacher) a uno più piccolo (student).', en: 'Distillation transfers knowledge from teacher to student model.' },
  'fine-tuning': { it: 'Fine-tuning: adatta un modello pre-addestrato a un compito o dominio specifico.', en: 'Fine-tuning adapts a pretrained model to a task.' },
  llm: { it: 'LLM: modello linguistico di grandi dimensioni, tipicamente basato su Transformer.', en: 'An LLM is a large Transformer-based language model.' },
  'machine learning': { it: 'Machine learning: migliorare prestazioni da dati senza regole scritte a mano per ogni caso.', en: 'Machine learning improves performance from data without hand-coded rules.' },
  'pre-training': { it: 'Pre-training: apprendimento generico su grandi corpus prima del fine-tuning.', en: 'Pre-training is large-scale generic learning before fine-tuning.' },
  'prompt engineering': { it: 'Prompt engineering: progettare istruzioni per risposte migliori senza riallenare i pesi.', en: 'Prompt engineering crafts instructions without retraining weights.' },
  'rete neurale': { it: 'Rete neurale: unità collegate da pesi addestrate tipicamente con backpropagation.', en: 'A neural network maps inputs via weighted layers.' },
  'superintelligenza artificiale': { it: 'ASI: ipotetica AI oltre le capacità umane nella maggior parte dei domini.', en: 'ASI is hypothetical AI beyond human cognitive ability.' },
  token: { it: 'Token: unità base del testo processata dai modelli linguistici (parola o sotto-parola).', en: 'A token is the basic text unit models process.' },
  transformer: { it: 'Il Transformer è l\'architettura base dei LLM moderni, basata su self-attention per modellare relazioni a lungo raggio nel testo.', en: 'The Transformer is the core architecture of modern LLMs, based on self-attention.' },
  'self-attention': { it: 'Self-Attention pesa le relazioni tra token; Multi-Head Attention usa più teste in parallelo per pattern diversi (sintassi, semantica).', en: 'Self-attention weighs token relations; multi-head runs several heads in parallel.' },
  'multi-head attention': { it: 'Multi-Head Attention: più teste di attention in parallelo che catturano tipi diversi di relazioni tra token.', en: 'Multi-head attention uses parallel attention heads for different patterns.' },
  rope: { it: 'RoPE (Rotary Positional Embeddings) codifica la posizione dei token ruotando le rappresentazioni, utile per contesti lunghi.', en: 'RoPE encodes token positions by rotating representations for long contexts.' },
  'positional encoding': { it: 'Positional Encoding: informa il modello sulla posizione dei token nella sequenza (assoluta, relativa o rotary/RoPE).', en: 'Positional encoding tells the model where tokens sit in the sequence.' },
  'mixture of experts': { it: 'Mixture of Experts (MoE): solo un sottoinsieme di esperti (sottoreti) si attiva per ogni input, aumentando capacità a costo selettivo.', en: 'MoE activates only a subset of expert subnetworks per input.' },
  'flash attention': { it: 'Flash Attention ottimizza l\'attention riducendo accessi alla memoria GPU e accelerando training e inference su sequenze lunghe.', en: 'Flash Attention optimizes attention by cutting GPU memory traffic.' },
  'residual connections': { it: 'Residual Connections: collegamenti di scorciatoia che stabilizzano l\'addestramento di reti profonde (assieme a LayerNorm/RMSNorm).', en: 'Residual connections stabilize deep network training.' },
  layernorm: { it: 'Layer Normalization / RMSNorm normalizzano le attivazioni per strato, stabilizzando training e inference.', en: 'LayerNorm/RMSNorm normalize activations per layer for stability.' },
  mamba: { it: 'Mamba / State Space Models (SSM): alternative ai Transformer per sequenze lunghe, con complessità quasi lineare.', en: 'Mamba/SSMs are near-linear alternatives to Transformers for long sequences.' },
  diffusion: { it: 'Diffusion Models generano dati (es. immagini) partendo da rumore e denoisando passo dopo passo.', en: 'Diffusion models generate data by iterative denoising from noise.' },
  vae: { it: 'VAE (Variational Autoencoder): modello generativo con spazio latente probabilistico.', en: 'A VAE is a generative model with a probabilistic latent space.' },
  gan: { it: 'GAN: generatore e discriminatore in competizione per produrre campioni realistici.', en: 'GANs pit a generator against a discriminator to make realistic samples.' },
  'context window': { it: 'Context Window: numero massimo di token (prompt + risposta) che il modello può considerare in una volta.', en: 'Context window is the max tokens a model can handle at once.' },
  'kv cache': { it: 'KV Cache: memorizza chiavi e valori dell\'attention già calcolati per accelerare la generazione token-per-token.', en: 'KV cache stores attention keys/values to speed autoregressive decoding.' },
  rlhf: { it: 'RLHF (Reinforcement Learning from Human Feedback) allinea il modello alle preferenze umane tramite ricompense da valutatori.', en: 'RLHF aligns models to human preferences via reward signals from raters.' },
  dpo: { it: 'DPO (Direct Preference Optimization) allinea su coppie preferenza/rifiuto senza un reward model separato.', en: 'DPO aligns on preference pairs without a separate reward model.' },
  lora: { it: 'LoRA / QLoRA / PEFT: fine-tuning efficiente addestrando poche matrici low-rank invece di tutti i pesi del modello.', en: 'LoRA/QLoRA/PEFT fine-tune efficiently via low-rank adapters.' },
  'gradient checkpointing': { it: 'Gradient Checkpointing ricalcola attivazioni al bisogno per risparmiare memoria in training; il clipping limita la norma del gradiente.', en: 'Gradient checkpointing trades compute for memory; clipping stabilizes grads.' },
  'mixed precision': { it: 'Mixed Precision (FP16/BF16/FP8): training/inference a precisione ridotta per velocità e meno memoria.', en: 'Mixed precision uses FP16/BF16/FP8 for speed and lower memory.' },
  quantizzazione: { it: 'Quantizzazione (INT8/INT4, GPTQ, AWQ, GGUF): riduce la precisione dei pesi per meno memoria e latenza in inference.', en: 'Quantization lowers weight precision for faster, smaller inference.' },
  'scaling laws': { it: 'Scaling Laws: relazioni empiriche tra dimensione del modello, quantità di dati, compute e performance attesa.', en: 'Scaling laws relate model size, data, compute and expected performance.' },
  'learning rate scheduler': { it: 'Learning Rate Scheduler (warmup, cosine decay): regola quanto velocemente il modello aggiorna i pesi durante l\'addestramento.', en: 'LR schedulers (warmup, cosine decay) control optimization step size.' },
  'catastrophic forgetting': { it: 'Catastrophic Forgetting: perdita di conoscenze precedenti quando si fine-tuna su nuovi compiti senza tecniche di continuità.', en: 'Catastrophic forgetting is loss of prior knowledge after fine-tuning on new tasks.' },
  gpu: { it: 'GPU / TPU / Tensor Cores: acceleratori hardware per training e inference; Tensor Cores ottimizzano matrici a bassa precisione.', en: 'GPUs/TPUs/Tensor Cores accelerate training and inference.' },
  'distributed training': { it: 'Distributed Training: Data/Tensor/Pipeline Parallelism distribuiscono dati o layer su più dispositivi.', en: 'Distributed training splits data or layers across devices.' },
  zero: { it: 'ZeRO (Zero Redundancy Optimizer): partiziona stati di ottimizzatore, gradienti e parametri tra GPU per ridurre memoria (DeepSpeed).', en: 'ZeRO partitions optimizer/grad/param state across GPUs to save memory.' },
  cuda: { it: 'CUDA / cuDNN: stack NVIDIA per calcolo parallelo su GPU e primitive ottimizzate di deep learning.', en: 'CUDA/cuDNN are NVIDIA stacks for GPU parallel compute and DL kernels.' },
  nvlink: { it: 'NVLink / InfiniBand: interconnessioni ad alta banda tra GPU o nodi cluster per training distribuito.', en: 'NVLink/InfiniBand provide high-bandwidth links for multi-GPU/node training.' },
  pytorch: { it: 'PyTorch, TensorFlow, JAX, DeepSpeed, Megatron-LM: framework e librerie per definire, addestrare e scalare modelli neurali.', en: 'PyTorch/TF/JAX/DeepSpeed/Megatron are frameworks for building and scaling models.' },
  vllm: { it: 'vLLM / TensorRT-LLM / Triton / ONNX Runtime: sistemi di serving ad alta throughput per LLM in produzione.', en: 'vLLM/TensorRT-LLM/Triton/ONNX serve LLMs at high throughput in production.' },
  kubernetes: { it: 'Kubernetes / Docker / Terraform: container, orchestrazione e infrastruttura come codice per deploy riproducibili.', en: 'Kubernetes, Docker and Terraform package and deploy infrastructure as code.' },
  'continuous batching': { it: 'Continuous Batching: inserisce nuove richieste nel batch in corso per massimizzare l\'uso GPU in serving.', en: 'Continuous batching inserts new requests into the running GPU batch.' },
  embedding: { it: 'Embedding: vettore numerico che rappresenta testo; similarità semantica ≈ prossimità nello spazio (es. cosine similarity).', en: 'An embedding is a numeric vector for text; proximity means semantic similarity.' },
  'vector database': { it: 'Vector Database (Pinecone, Milvus, Qdrant, Weaviate, FAISS, Chroma): ricerca per similarità su embedding.', en: 'Vector DBs store embeddings for fast similarity search.' },
  ann: { it: 'ANN (Approximate Nearest Neighbor) con indici HNSW o IVF trova vettori simili in modo veloce su grandi collezioni.', en: 'ANN methods (HNSW, IVF) find approximate nearest neighbors quickly.' },
  rag: { it: 'RAG (Retrieval-Augmented Generation): recupera documenti rilevanti e li usa come contesto per risposte ancorate alle fonti. È il cuore di WidowBlue.', en: 'RAG retrieves documents and grounds generation on them. Core of WidowBlue.' },
  chunking: { it: 'Chunking: suddivide i documenti in segmenti adatti a embedding e retrieval; dimensione e overlap influenzano la qualità RAG.', en: 'Chunking splits documents into passages for embedding and retrieval.' },
  tokenizzazione: { it: 'Tokenizzazione (BPE, SentencePiece): converte il testo in token; algoritmi comuni nei tokenizer dei LLM.', en: 'Tokenization (BPE, SentencePiece) converts text into model tokens.' },
  'cosine similarity': { it: 'Cosine Similarity: misura di similarità tra vettori basata sull\'angolo, usata per confrontare embedding.', en: 'Cosine similarity measures vector angle similarity for embeddings.' },
  etl: { it: 'Data Pipeline / ETL: flussi Extract-Transform-Load per preparare, pulire e caricare dati di training o knowledge base.', en: 'ETL pipelines extract, transform and load training or KB data.' },
  deduplicazione: { it: 'Deduplicazione dati: rimozione di testi duplicati o quasi-duplicati per migliorare training e retrieval.', en: 'Deduplication removes duplicate or near-duplicate texts.' },
  langchain: { it: 'LangChain / LlamaIndex: framework per orchestrare LLM, tool, memoria e indici documentali in app agentiche e RAG.', en: 'LangChain/LlamaIndex orchestrate LLMs, tools, memory and document indexes.' },
  'function calling': { it: 'Function Calling / Tool Use: il modello invoca funzioni o API strutturate invece di rispondere solo a testo libero.', en: 'Function calling lets the model invoke structured tools and APIs.' },
  'agenti multi-step': { it: 'Agenti autonomi multi-step: pianificano più passi, usano tool e verificano risultati prima della risposta finale.', en: 'Multi-step agents plan, use tools and verify before answering.' },
  'semantic caching': { it: 'Semantic Caching (es. Redis): cache di risposte o embedding basata su similarità semantica della query, non solo match esatto.', en: 'Semantic caching stores answers by query similarity, not exact match only.' },
  fastapi: { it: 'Orchestrazione API (FastAPI, gRPC): backend che coordina modelli, tool e servizi via HTTP o RPC.', en: 'FastAPI/gRPC backends orchestrate models, tools and services.' },
  benchmark: { it: 'Benchmark (MMLU, HellaSwag, GSM8K, HumanEval): suite di test per conoscenze, ragionamento, matematica e codice dei modelli.', en: 'Benchmarks like MMLU, GSM8K, HumanEval measure model skills.' },
  'hallucination rate': { it: 'Hallucination Rate: tasso di risposte plausible ma non fondate; si riduce con RAG, citazioni e guardrail.', en: 'Hallucination rate measures ungrounded but plausible outputs.' },
  alignment: { it: 'Alignment / Constitutional AI: tecniche per allineare il comportamento del modello a valori e regole.', en: 'Alignment/Constitutional AI steers models toward desired values and rules.' },
  'red teaming': { it: 'Red Teaming: test avversariali deliberati per scoprire fallimenti di sicurezza, bias o comportamenti indesiderati.', en: 'Red teaming adversarially probes models for safety failures.' },
  'prompt injection': { it: 'Prompt Injection: input malevoli che tentano di sovrascrivere istruzioni di sistema o far agire il modello fuori policy.', en: 'Prompt injection tries to override system instructions via hostile input.' },
  guardrails: { it: 'Guardrails: vincoli e filtri (policy, classificatori, regole) che limitano output non sicuri o fuori dominio.', en: 'Guardrails constrain unsafe or off-policy model outputs.' },
  interpretability: { it: 'Interpretability: metodi per capire perché un modello ha prodotto una certa uscita (attenzione, attribution, circuiti).', en: 'Interpretability explains why a model produced a given output.' },
};

export const GLOSSARY_ALIASES = [
  ['addestramento', /\b(addestramento|training)\b/i],
  ['agi', /\bagi\b|intelligenza generale/i],
  ['agente ai', /\bagente\s*ai\b|\bai\s*agent\b/i],
  ['ai generativa', /ai\s*generativa|generative\s*ai/i],
  ['allucinazione', /allucinazion|hallucin/i],
  ['bias', /\bbias\b|distorsion/i],
  ['chain of thought', /chain\s*of\s*thought|catena del pensier/i],
  ['dataset', /\bdataset\b/i],
  ['deep learning', /deep\s*learning/i],
  ['distillazione', /distillazion|knowledge\s*distillation/i],
  ['fine-tuning', /fine[\s-]?tuning/i],
  ['llm', /\bllm\b|large language model/i],
  ['machine learning', /machine\s*learning|apprendimento automatico/i],
  ['pre-training', /pre[\s-]?training|pretraining/i],
  ['prompt engineering', /prompt\s*engineering/i],
  ['rete neurale', /rete\s*neural|neural\s*network/i],
  ['superintelligenza artificiale', /superintelligen|\basi\b/i],
  ['token', /\btoken\b(?!izz)/i],
  ['transformer', /\btransformers?\b/i],
  ['self-attention', /self[\s-]?attention/i],
  ['multi-head attention', /multi[\s-]?head\s*attention/i],
  ['rope', /\brope\b|rotary\s*positional/i],
  ['positional encoding', /positional\s*encoding/i],
  ['mixture of experts', /mixture\s*of\s*experts|\bmoe\b/i],
  ['flash attention', /flash\s*attention/i],
  ['residual connections', /residual\s*connection|layer\s*norm|rmsnorm/i],
  ['layernorm', /layernorm|rms\s*norm/i],
  ['mamba', /\bmamba\b|state\s*space\s*model|\bssm\b/i],
  ['diffusion', /diffusion\s*model/i],
  ['vae', /\bvae\b|variational\s*autoencoder/i],
  ['gan', /\bgan\b|generative\s*adversarial/i],
  ['context window', /context\s*window|finestra\s*di\s*contesto/i],
  ['kv cache', /kv\s*cache|key[\s-]?value\s*cache/i],
  ['rlhf', /\brlhf\b|reinforcement\s*learning\s*from\s*human/i],
  ['dpo', /\bdpo\b|direct\s*preference\s*optimization/i],
  ['lora', /\blora\b|\bqlora\b|\bpeft\b/i],
  ['gradient checkpointing', /gradient\s*checkpoint|gradient\s*clipping/i],
  ['mixed precision', /mixed\s*precision|\bfp16\b|\bbf16\b|\bfp8\b/i],
  ['quantizzazione', /quantizzaz|\bgptq\b|\bawq\b|\bgguf\b|\bint4\b|\bint8\b/i],
  ['scaling laws', /scaling\s*laws?/i],
  ['learning rate scheduler', /learning\s*rate|cosine\s*decay|warmup/i],
  ['catastrophic forgetting', /catastrophic\s*forgetting|dimenticanza\s*catastrofica/i],
  ['gpu', /\bgpu\b|\btpu\b|tensor\s*cores?/i],
  ['distributed training', /distributed\s*training|data\s*parallel|tensor\s*parallel|pipeline\s*parallel/i],
  ['zero', /\bzero\b.*optim|zero\s*redundancy/i],
  ['cuda', /\bcuda\b|\bcudnn\b/i],
  ['nvlink', /\bnvlink\b|infiniband/i],
  ['pytorch', /\bpytorch\b|\btensorflow\b|\bjax\b|deepspeed|megatron/i],
  ['vllm', /\bvllm\b|tensorrt[\s-]?llm|\btriton\b|onnx\s*runtime/i],
  ['kubernetes', /\bkubernetes\b|\bk8s\b|\bdocker\b|\bterraform\b/i],
  ['continuous batching', /continuous\s*batching/i],
  ['embedding', /\bembeddings?\b/i],
  ['vector database', /vector\s*database|\bpinecone\b|\bmilvus\b|\bqdrant\b|\bweaviate\b|\bfaiss\b|\bchroma\b/i],
  ['ann', /\bann\b|nearest\s*neighbor|\bhnsw\b|\bivf\b/i],
  ['rag', /\brag\b|retrieval[\s-]?augmented/i],
  ['chunking', /\bchunking\b|\bchunks?\b/i],
  ['tokenizzazione', /tokenizzaz|\bbpe\b|sentencepiece/i],
  ['cosine similarity', /cosine\s*similarity|similarit[aà]\s*coseno/i],
  ['etl', /\betl\b|data\s*pipeline/i],
  ['deduplicazione', /deduplic/i],
  ['langchain', /langchain|llamaindex/i],
  ['function calling', /function\s*calling|tool\s*use/i],
  ['agenti multi-step', /agenti?\s*autonomi|multi[\s-]?step\s*agent/i],
  ['semantic caching', /semantic\s*cach/i],
  ['fastapi', /\bfastapi\b|\bgrpc\b/i],
  ['benchmark', /\bmmlu\b|hellaswag|\bgsm8k\b|humaneval|benchmark/i],
  ['hallucination rate', /hallucination\s*rate/i],
  ['alignment', /\balignment\b|constitutional\s*ai|allineamento/i],
  ['red teaming', /red\s*teaming/i],
  ['prompt injection', /prompt\s*injection/i],
  ['guardrails', /guardrails?/i],
  ['interpretability', /interpretabilit|explainabilit/i],
];
