/**
 * WidowBlue – generazione video via JSON2Video
 * Secret: JSON2VIDEO_API_KEY (header x-api-key)
 * Docs: https://json2video.com/docs/api/
 */

export function isVideoRequest(prompt) {
  const t = String(prompt || '').toLowerCase();
  return (
    /\b(genera|generami|crea|creami|fai|make|generate|create)\b[\s\S]{0,80}\b(video|clip|movie|filmato|reel|short)\b/i.test(t) ||
    /\b(video|clip|movie|filmato)\b[\s\S]{0,40}\b(di|of|about|su|per|con)\b/i.test(t) ||
    /^(genera|generami|crea|fai|make|generate)\s+(un[oa]?\s+)?(video|clip|movie)/i.test(t)
  );
}

export function extractVideoPrompt(prompt) {
  let s = String(prompt || '').trim();
  s = s
    .replace(/^(per\s+favore\s+|please\s+)/i, '')
    .replace(
      /^(generami|genera|crea|creami|fai|make|generate|create)\s+(un[oa]?\s+)?(video|clip|movie|filmato|reel|short)\s*(di|of|about|su|per|con|:)?\s*/i,
      ''
    )
    .replace(/^(un[oa]?\s+)?(video|clip|movie|filmato)\s*(di|of|about|su|per|:)?\s*/i, '')
    .trim();
  if (!s || s.length < 3) s = String(prompt || '').trim();
  return s.slice(0, 800);
}

function buildMovieJson(text, lang) {
  const title = String(text || 'WidowBlue').slice(0, 120);
  return {
    resolution: 'full-hd',
    quality: 'high',
    scenes: [
      {
        duration: 8,
        'background-color': '#040a12',
        elements: [
          {
            type: 'text',
            text: title,
            duration: 8,
            'font-size': 64,
            'font-color': '#4de1ff',
            'font-family': 'Roboto',
            style: '001',
            x: '50%',
            y: '45%',
            'text-align': 'center',
          },
          {
            type: 'text',
            text: lang === 'it' ? 'Generato da WidowBlue' : 'Generated by WidowBlue',
            duration: 8,
            'font-size': 28,
            'font-color': '#5f8296',
            x: '50%',
            y: '70%',
            'text-align': 'center',
          },
        ],
      },
    ],
  };
}

export async function generateVideo(prompt, opts = {}) {
  const env = opts.env || {};
  const lang = opts.lang || 'it';
  const apiKey = env.JSON2VIDEO_API_KEY || env.J2V_API_KEY;
  if (!apiKey) {
    return {
      ok: false,
      error: 'missing_json2video_key',
      message:
        lang === 'it'
          ? 'Configura il secret JSON2VIDEO_API_KEY su Cloudflare per generare video.'
          : 'Set JSON2VIDEO_API_KEY secret on Cloudflare to generate videos.',
    };
  }

  const subject = extractVideoPrompt(prompt);
  const body = opts.movieJson && typeof opts.movieJson === 'object' ? opts.movieJson : buildMovieJson(subject, lang);

  const res = await fetch('https://api.json2video.com/v2/movies', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => '');
    return {
      ok: false,
      error: 'json2video_http_' + res.status,
      message: String(errText).slice(0, 300) || 'JSON2Video request failed',
    };
  }

  const data = await res.json();
  const project = data.project || data.projectId || (data.movie && data.movie.project);
  if (!project) {
    return { ok: false, error: 'no_project_id', message: JSON.stringify(data).slice(0, 200), raw: data };
  }

  const wait = opts.wait !== false;
  let movie = null;
  if (wait) {
    const maxTries = Math.min(Number(opts.maxPolls) || 8, 12);
    for (let i = 0; i < maxTries; i++) {
      await sleep(i === 0 ? 2000 : 4000);
      movie = await pollMovie(apiKey, project);
      if (movie && (movie.status === 'done' || movie.status === 'error' || movie.status === 'timeout')) break;
    }
  }

  if (movie && movie.status === 'done') {
    const url = movie.url || movie.result || (movie.exports && movie.exports[0] && movie.exports[0].url);
    return {
      ok: true,
      project,
      status: 'done',
      url: url || null,
      videoUrl: url || null,
      message:
        lang === 'it'
          ? 'Video generato: ' + subject.slice(0, 80)
          : 'Video generated: ' + subject.slice(0, 80),
      subject,
      provider: 'json2video',
    };
  }

  if (movie && movie.status === 'error') {
    return {
      ok: false,
      project,
      status: 'error',
      message: movie.message || (lang === 'it' ? 'Errore nel render video.' : 'Video render error.'),
      provider: 'json2video',
    };
  }

  return {
    ok: true,
    project,
    status: (movie && movie.status) || 'queued',
    url: null,
    videoUrl: null,
    message:
      lang === 'it'
        ? 'Video in elaborazione (project: ' + project + '). Riprova tra qualche secondo o usa /api/video/status.'
        : 'Video processing (project: ' + project + '). Retry shortly or poll /api/video/status.',
    subject,
    provider: 'json2video',
  };
}

export async function getVideoStatus(projectId, opts = {}) {
  const env = opts.env || {};
  const apiKey = env.JSON2VIDEO_API_KEY || env.J2V_API_KEY;
  if (!apiKey) return { ok: false, error: 'missing_json2video_key' };
  if (!projectId) return { ok: false, error: 'missing_project' };
  const movie = await pollMovie(apiKey, projectId);
  if (!movie) return { ok: false, error: 'poll_failed', project: projectId };
  const url = movie.url || movie.result || null;
  return {
    ok: true,
    project: projectId,
    status: movie.status,
    url,
    videoUrl: url,
    message: movie.message || null,
    provider: 'json2video',
  };
}

async function pollMovie(apiKey, projectId) {
  const res = await fetch(
    'https://api.json2video.com/v2/movies?project=' + encodeURIComponent(projectId),
    { headers: { 'x-api-key': apiKey, Accept: 'application/json' } }
  );
  if (!res.ok) return null;
  const data = await res.json();
  return data.movie || data;
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}
